// All RPC definitions
// proto/matrimonial.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: matrimonial.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Division struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NameEn        string                 `protobuf:"bytes,2,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	NameBn        string                 `protobuf:"bytes,3,opt,name=name_bn,json=nameBn,proto3" json:"name_bn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Division) Reset() {
	*x = Division{}
	mi := &file_matrimonial_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Division) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Division) ProtoMessage() {}

func (x *Division) ProtoReflect() protoreflect.Message {
	mi := &file_matrimonial_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Division.ProtoReflect.Descriptor instead.
func (*Division) Descriptor() ([]byte, []int) {
	return file_matrimonial_proto_rawDescGZIP(), []int{0}
}

func (x *Division) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Division) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *Division) GetNameBn() string {
	if x != nil {
		return x.NameBn
	}
	return ""
}

type District struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DivisionId    int64                  `protobuf:"varint,2,opt,name=division_id,json=divisionId,proto3" json:"division_id,omitempty"`
	NameEn        string                 `protobuf:"bytes,3,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	NameBn        string                 `protobuf:"bytes,4,opt,name=name_bn,json=nameBn,proto3" json:"name_bn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *District) Reset() {
	*x = District{}
	mi := &file_matrimonial_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *District) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*District) ProtoMessage() {}

func (x *District) ProtoReflect() protoreflect.Message {
	mi := &file_matrimonial_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use District.ProtoReflect.Descriptor instead.
func (*District) Descriptor() ([]byte, []int) {
	return file_matrimonial_proto_rawDescGZIP(), []int{1}
}

func (x *District) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *District) GetDivisionId() int64 {
	if x != nil {
		return x.DivisionId
	}
	return 0
}

func (x *District) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *District) GetNameBn() string {
	if x != nil {
		return x.NameBn
	}
	return ""
}

type Upazila struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DistrictId    int64                  `protobuf:"varint,2,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	NameEn        string                 `protobuf:"bytes,3,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	NameBn        string                 `protobuf:"bytes,4,opt,name=name_bn,json=nameBn,proto3" json:"name_bn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Upazila) Reset() {
	*x = Upazila{}
	mi := &file_matrimonial_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Upazila) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upazila) ProtoMessage() {}

func (x *Upazila) ProtoReflect() protoreflect.Message {
	mi := &file_matrimonial_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upazila.ProtoReflect.Descriptor instead.
func (*Upazila) Descriptor() ([]byte, []int) {
	return file_matrimonial_proto_rawDescGZIP(), []int{2}
}

func (x *Upazila) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Upazila) GetDistrictId() int64 {
	if x != nil {
		return x.DistrictId
	}
	return 0
}

func (x *Upazila) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *Upazila) GetNameBn() string {
	if x != nil {
		return x.NameBn
	}
	return ""
}

type GetDivisionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDivisionsRequest) Reset() {
	*x = GetDivisionsRequest{}
	mi := &file_matrimonial_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDivisionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDivisionsRequest) ProtoMessage() {}

func (x *GetDivisionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matrimonial_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDivisionsRequest.ProtoReflect.Descriptor instead.
func (*GetDivisionsRequest) Descriptor() ([]byte, []int) {
	return file_matrimonial_proto_rawDescGZIP(), []int{3}
}

type GetDivisionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Divisions     []*Division            `protobuf:"bytes,1,rep,name=divisions,proto3" json:"divisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDivisionsResponse) Reset() {
	*x = GetDivisionsResponse{}
	mi := &file_matrimonial_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDivisionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDivisionsResponse) ProtoMessage() {}

func (x *GetDivisionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matrimonial_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDivisionsResponse.ProtoReflect.Descriptor instead.
func (*GetDivisionsResponse) Descriptor() ([]byte, []int) {
	return file_matrimonial_proto_rawDescGZIP(), []int{4}
}

func (x *GetDivisionsResponse) GetDivisions() []*Division {
	if x != nil {
		return x.Divisions
	}
	return nil
}

type GetDistrictsByDivisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DivisionId    int64                  `protobuf:"varint,1,opt,name=division_id,json=divisionId,proto3" json:"division_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDistrictsByDivisionRequest) Reset() {
	*x = GetDistrictsByDivisionRequest{}
	mi := &file_matrimonial_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDistrictsByDivisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistrictsByDivisionRequest) ProtoMessage() {}

func (x *GetDistrictsByDivisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matrimonial_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistrictsByDivisionRequest.ProtoReflect.Descriptor instead.
func (*GetDistrictsByDivisionRequest) Descriptor() ([]byte, []int) {
	return file_matrimonial_proto_rawDescGZIP(), []int{5}
}

func (x *GetDistrictsByDivisionRequest) GetDivisionId() int64 {
	if x != nil {
		return x.DivisionId
	}
	return 0
}

type GetDistrictsByDivisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Districts     []*District            `protobuf:"bytes,1,rep,name=districts,proto3" json:"districts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDistrictsByDivisionResponse) Reset() {
	*x = GetDistrictsByDivisionResponse{}
	mi := &file_matrimonial_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDistrictsByDivisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistrictsByDivisionResponse) ProtoMessage() {}

func (x *GetDistrictsByDivisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matrimonial_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistrictsByDivisionResponse.ProtoReflect.Descriptor instead.
func (*GetDistrictsByDivisionResponse) Descriptor() ([]byte, []int) {
	return file_matrimonial_proto_rawDescGZIP(), []int{6}
}

func (x *GetDistrictsByDivisionResponse) GetDistricts() []*District {
	if x != nil {
		return x.Districts
	}
	return nil
}

type GetUpazilasByDistrictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DistrictId    int64                  `protobuf:"varint,1,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpazilasByDistrictRequest) Reset() {
	*x = GetUpazilasByDistrictRequest{}
	mi := &file_matrimonial_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpazilasByDistrictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpazilasByDistrictRequest) ProtoMessage() {}

func (x *GetUpazilasByDistrictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matrimonial_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpazilasByDistrictRequest.ProtoReflect.Descriptor instead.
func (*GetUpazilasByDistrictRequest) Descriptor() ([]byte, []int) {
	return file_matrimonial_proto_rawDescGZIP(), []int{7}
}

func (x *GetUpazilasByDistrictRequest) GetDistrictId() int64 {
	if x != nil {
		return x.DistrictId
	}
	return 0
}

type GetUpazilasByDistrictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upazilas      []*Upazila             `protobuf:"bytes,1,rep,name=upazilas,proto3" json:"upazilas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpazilasByDistrictResponse) Reset() {
	*x = GetUpazilasByDistrictResponse{}
	mi := &file_matrimonial_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpazilasByDistrictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpazilasByDistrictResponse) ProtoMessage() {}

func (x *GetUpazilasByDistrictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matrimonial_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpazilasByDistrictResponse.ProtoReflect.Descriptor instead.
func (*GetUpazilasByDistrictResponse) Descriptor() ([]byte, []int) {
	return file_matrimonial_proto_rawDescGZIP(), []int{8}
}

func (x *GetUpazilasByDistrictResponse) GetUpazilas() []*Upazila {
	if x != nil {
		return x.Upazilas
	}
	return nil
}

type Qualification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CommonName    string                 `protobuf:"bytes,3,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	LevelId       int64                  `protobuf:"varint,4,opt,name=level_id,json=levelId,proto3" json:"level_id,omitempty"`
	StreamId      int64                  `protobuf:"varint,5,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Qualification) Reset() {
	*x = Qualification{}
	mi := &file_matrimonial_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Qualification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Qualification) ProtoMessage() {}

func (x *Qualification) ProtoReflect() protoreflect.Message {
	mi := &file_matrimonial_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Qualification.ProtoReflect.Descriptor instead.
func (*Qualification) Descriptor() ([]byte, []int) {
	return file_matrimonial_proto_rawDescGZIP(), []int{9}
}

func (x *Qualification) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Qualification) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Qualification) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *Qualification) GetLevelId() int64 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *Qualification) GetStreamId() int64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

type GetQualificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQualificationsRequest) Reset() {
	*x = GetQualificationsRequest{}
	mi := &file_matrimonial_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQualificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQualificationsRequest) ProtoMessage() {}

func (x *GetQualificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matrimonial_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQualificationsRequest.ProtoReflect.Descriptor instead.
func (*GetQualificationsRequest) Descriptor() ([]byte, []int) {
	return file_matrimonial_proto_rawDescGZIP(), []int{10}
}

type GetQualificationsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Qualifications []*Qualification       `protobuf:"bytes,1,rep,name=qualifications,proto3" json:"qualifications,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetQualificationsResponse) Reset() {
	*x = GetQualificationsResponse{}
	mi := &file_matrimonial_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQualificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQualificationsResponse) ProtoMessage() {}

func (x *GetQualificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matrimonial_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQualificationsResponse.ProtoReflect.Descriptor instead.
func (*GetQualificationsResponse) Descriptor() ([]byte, []int) {
	return file_matrimonial_proto_rawDescGZIP(), []int{11}
}

func (x *GetQualificationsResponse) GetQualifications() []*Qualification {
	if x != nil {
		return x.Qualifications
	}
	return nil
}

type StaticOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaticOption) Reset() {
	*x = StaticOption{}
	mi := &file_matrimonial_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticOption) ProtoMessage() {}

func (x *StaticOption) ProtoReflect() protoreflect.Message {
	mi := &file_matrimonial_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticOption.ProtoReflect.Descriptor instead.
func (*StaticOption) Descriptor() ([]byte, []int) {
	return file_matrimonial_proto_rawDescGZIP(), []int{12}
}

func (x *StaticOption) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StaticOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetReligionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReligionsRequest) Reset() {
	*x = GetReligionsRequest{}
	mi := &file_matrimonial_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReligionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReligionsRequest) ProtoMessage() {}

func (x *GetReligionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matrimonial_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReligionsRequest.ProtoReflect.Descriptor instead.
func (*GetReligionsRequest) Descriptor() ([]byte, []int) {
	return file_matrimonial_proto_rawDescGZIP(), []int{13}
}

type GetReligionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Religions     []*StaticOption        `protobuf:"bytes,1,rep,name=religions,proto3" json:"religions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReligionsResponse) Reset() {
	*x = GetReligionsResponse{}
	mi := &file_matrimonial_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReligionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReligionsResponse) ProtoMessage() {}

func (x *GetReligionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matrimonial_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReligionsResponse.ProtoReflect.Descriptor instead.
func (*GetReligionsResponse) Descriptor() ([]byte, []int) {
	return file_matrimonial_proto_rawDescGZIP(), []int{14}
}

func (x *GetReligionsResponse) GetReligions() []*StaticOption {
	if x != nil {
		return x.Religions
	}
	return nil
}

type GetProfessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfessionsRequest) Reset() {
	*x = GetProfessionsRequest{}
	mi := &file_matrimonial_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfessionsRequest) ProtoMessage() {}

func (x *GetProfessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matrimonial_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfessionsRequest.ProtoReflect.Descriptor instead.
func (*GetProfessionsRequest) Descriptor() ([]byte, []int) {
	return file_matrimonial_proto_rawDescGZIP(), []int{15}
}

type GetProfessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Professions   []*StaticOption        `protobuf:"bytes,1,rep,name=professions,proto3" json:"professions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfessionsResponse) Reset() {
	*x = GetProfessionsResponse{}
	mi := &file_matrimonial_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfessionsResponse) ProtoMessage() {}

func (x *GetProfessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matrimonial_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfessionsResponse.ProtoReflect.Descriptor instead.
func (*GetProfessionsResponse) Descriptor() ([]byte, []int) {
	return file_matrimonial_proto_rawDescGZIP(), []int{16}
}

func (x *GetProfessionsResponse) GetProfessions() []*StaticOption {
	if x != nil {
		return x.Professions
	}
	return nil
}

type GetMaritalStatusesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMaritalStatusesRequest) Reset() {
	*x = GetMaritalStatusesRequest{}
	mi := &file_matrimonial_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaritalStatusesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaritalStatusesRequest) ProtoMessage() {}

func (x *GetMaritalStatusesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matrimonial_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaritalStatusesRequest.ProtoReflect.Descriptor instead.
func (*GetMaritalStatusesRequest) Descriptor() ([]byte, []int) {
	return file_matrimonial_proto_rawDescGZIP(), []int{17}
}

type GetMaritalStatusesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaritalStatuses []*StaticOption        `protobuf:"bytes,1,rep,name=marital_statuses,json=maritalStatuses,proto3" json:"marital_statuses,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetMaritalStatusesResponse) Reset() {
	*x = GetMaritalStatusesResponse{}
	mi := &file_matrimonial_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaritalStatusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaritalStatusesResponse) ProtoMessage() {}

func (x *GetMaritalStatusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matrimonial_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaritalStatusesResponse.ProtoReflect.Descriptor instead.
func (*GetMaritalStatusesResponse) Descriptor() ([]byte, []int) {
	return file_matrimonial_proto_rawDescGZIP(), []int{18}
}

func (x *GetMaritalStatusesResponse) GetMaritalStatuses() []*StaticOption {
	if x != nil {
		return x.MaritalStatuses
	}
	return nil
}

var File_matrimonial_proto protoreflect.FileDescriptor

const file_matrimonial_proto_rawDesc = "" +
	"\n" +
	"\x11matrimonial.proto\x12\x05proto\x1a\x1cgoogle/api/annotations.proto\"L\n" +
	"\bDivision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\aname_en\x18\x02 \x01(\tR\x06nameEn\x12\x17\n" +
	"\aname_bn\x18\x03 \x01(\tR\x06nameBn\"m\n" +
	"\bDistrict\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vdivision_id\x18\x02 \x01(\x03R\n" +
	"divisionId\x12\x17\n" +
	"\aname_en\x18\x03 \x01(\tR\x06nameEn\x12\x17\n" +
	"\aname_bn\x18\x04 \x01(\tR\x06nameBn\"l\n" +
	"\aUpazila\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vdistrict_id\x18\x02 \x01(\x03R\n" +
	"districtId\x12\x17\n" +
	"\aname_en\x18\x03 \x01(\tR\x06nameEn\x12\x17\n" +
	"\aname_bn\x18\x04 \x01(\tR\x06nameBn\"\x15\n" +
	"\x13GetDivisionsRequest\"E\n" +
	"\x14GetDivisionsResponse\x12-\n" +
	"\tdivisions\x18\x01 \x03(\v2\x0f.proto.DivisionR\tdivisions\"@\n" +
	"\x1dGetDistrictsByDivisionRequest\x12\x1f\n" +
	"\vdivision_id\x18\x01 \x01(\x03R\n" +
	"divisionId\"O\n" +
	"\x1eGetDistrictsByDivisionResponse\x12-\n" +
	"\tdistricts\x18\x01 \x03(\v2\x0f.proto.DistrictR\tdistricts\"?\n" +
	"\x1cGetUpazilasByDistrictRequest\x12\x1f\n" +
	"\vdistrict_id\x18\x01 \x01(\x03R\n" +
	"districtId\"K\n" +
	"\x1dGetUpazilasByDistrictResponse\x12*\n" +
	"\bupazilas\x18\x01 \x03(\v2\x0e.proto.UpazilaR\bupazilas\"\x8c\x01\n" +
	"\rQualification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcommon_name\x18\x03 \x01(\tR\n" +
	"commonName\x12\x19\n" +
	"\blevel_id\x18\x04 \x01(\x03R\alevelId\x12\x1b\n" +
	"\tstream_id\x18\x05 \x01(\x03R\bstreamId\"\x1a\n" +
	"\x18GetQualificationsRequest\"Y\n" +
	"\x19GetQualificationsResponse\x12<\n" +
	"\x0equalifications\x18\x01 \x03(\v2\x14.proto.QualificationR\x0equalifications\"2\n" +
	"\fStaticOption\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x15\n" +
	"\x13GetReligionsRequest\"I\n" +
	"\x14GetReligionsResponse\x121\n" +
	"\treligions\x18\x01 \x03(\v2\x13.proto.StaticOptionR\treligions\"\x17\n" +
	"\x15GetProfessionsRequest\"O\n" +
	"\x16GetProfessionsResponse\x125\n" +
	"\vprofessions\x18\x01 \x03(\v2\x13.proto.StaticOptionR\vprofessions\"\x1b\n" +
	"\x19GetMaritalStatusesRequest\"\\\n" +
	"\x1aGetMaritalStatusesResponse\x12>\n" +
	"\x10marital_statuses\x18\x01 \x03(\v2\x13.proto.StaticOptionR\x0fmaritalStatuses2\xc5\x03\n" +
	"\x0fLocationService\x12l\n" +
	"\fGetDivisions\x12\x1a.proto.GetDivisionsRequest\x1a\x1b.proto.GetDivisionsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/locations/divisions\x12\xa2\x01\n" +
	"\x16GetDistrictsByDivision\x12$.proto.GetDistrictsByDivisionRequest\x1a%.proto.GetDistrictsByDivisionResponse\";\x82\xd3\xe4\x93\x025\x123/api/v1/locations/divisions/{division_id}/districts\x12\x9e\x01\n" +
	"\x15GetUpazilasByDistrict\x12#.proto.GetUpazilasByDistrictRequest\x1a$.proto.GetUpazilasByDistrictResponse\":\x82\xd3\xe4\x93\x024\x122/api/v1/locations/districts/{district_id}/upazilas2\x95\x01\n" +
	"\x10EducationService\x12\x80\x01\n" +
	"\x11GetQualifications\x12\x1f.proto.GetQualificationsRequest\x1a .proto.GetQualificationsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /api/v1/education/qualifications2\xf6\x02\n" +
	"\x11StaticDataService\x12i\n" +
	"\fGetReligions\x12\x1a.proto.GetReligionsRequest\x1a\x1b.proto.GetReligionsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/static/religions\x12q\n" +
	"\x0eGetProfessions\x12\x1c.proto.GetProfessionsRequest\x1a\x1d.proto.GetProfessionsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/static/professions\x12\x82\x01\n" +
	"\x12GetMaritalStatuses\x12 .proto.GetMaritalStatusesRequest\x1a!.proto.GetMaritalStatusesResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/static/marital-statusesB(Z&matrimonial-service/internal/api/protob\x06proto3"

var (
	file_matrimonial_proto_rawDescOnce sync.Once
	file_matrimonial_proto_rawDescData []byte
)

func file_matrimonial_proto_rawDescGZIP() []byte {
	file_matrimonial_proto_rawDescOnce.Do(func() {
		file_matrimonial_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matrimonial_proto_rawDesc), len(file_matrimonial_proto_rawDesc)))
	})
	return file_matrimonial_proto_rawDescData
}

var file_matrimonial_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_matrimonial_proto_goTypes = []any{
	(*Division)(nil),                       // 0: proto.Division
	(*District)(nil),                       // 1: proto.District
	(*Upazila)(nil),                        // 2: proto.Upazila
	(*GetDivisionsRequest)(nil),            // 3: proto.GetDivisionsRequest
	(*GetDivisionsResponse)(nil),           // 4: proto.GetDivisionsResponse
	(*GetDistrictsByDivisionRequest)(nil),  // 5: proto.GetDistrictsByDivisionRequest
	(*GetDistrictsByDivisionResponse)(nil), // 6: proto.GetDistrictsByDivisionResponse
	(*GetUpazilasByDistrictRequest)(nil),   // 7: proto.GetUpazilasByDistrictRequest
	(*GetUpazilasByDistrictResponse)(nil),  // 8: proto.GetUpazilasByDistrictResponse
	(*Qualification)(nil),                  // 9: proto.Qualification
	(*GetQualificationsRequest)(nil),       // 10: proto.GetQualificationsRequest
	(*GetQualificationsResponse)(nil),      // 11: proto.GetQualificationsResponse
	(*StaticOption)(nil),                   // 12: proto.StaticOption
	(*GetReligionsRequest)(nil),            // 13: proto.GetReligionsRequest
	(*GetReligionsResponse)(nil),           // 14: proto.GetReligionsResponse
	(*GetProfessionsRequest)(nil),          // 15: proto.GetProfessionsRequest
	(*GetProfessionsResponse)(nil),         // 16: proto.GetProfessionsResponse
	(*GetMaritalStatusesRequest)(nil),      // 17: proto.GetMaritalStatusesRequest
	(*GetMaritalStatusesResponse)(nil),     // 18: proto.GetMaritalStatusesResponse
}
var file_matrimonial_proto_depIdxs = []int32{
	0,  // 0: proto.GetDivisionsResponse.divisions:type_name -> proto.Division
	1,  // 1: proto.GetDistrictsByDivisionResponse.districts:type_name -> proto.District
	2,  // 2: proto.GetUpazilasByDistrictResponse.upazilas:type_name -> proto.Upazila
	9,  // 3: proto.GetQualificationsResponse.qualifications:type_name -> proto.Qualification
	12, // 4: proto.GetReligionsResponse.religions:type_name -> proto.StaticOption
	12, // 5: proto.GetProfessionsResponse.professions:type_name -> proto.StaticOption
	12, // 6: proto.GetMaritalStatusesResponse.marital_statuses:type_name -> proto.StaticOption
	3,  // 7: proto.LocationService.GetDivisions:input_type -> proto.GetDivisionsRequest
	5,  // 8: proto.LocationService.GetDistrictsByDivision:input_type -> proto.GetDistrictsByDivisionRequest
	7,  // 9: proto.LocationService.GetUpazilasByDistrict:input_type -> proto.GetUpazilasByDistrictRequest
	10, // 10: proto.EducationService.GetQualifications:input_type -> proto.GetQualificationsRequest
	13, // 11: proto.StaticDataService.GetReligions:input_type -> proto.GetReligionsRequest
	15, // 12: proto.StaticDataService.GetProfessions:input_type -> proto.GetProfessionsRequest
	17, // 13: proto.StaticDataService.GetMaritalStatuses:input_type -> proto.GetMaritalStatusesRequest
	4,  // 14: proto.LocationService.GetDivisions:output_type -> proto.GetDivisionsResponse
	6,  // 15: proto.LocationService.GetDistrictsByDivision:output_type -> proto.GetDistrictsByDivisionResponse
	8,  // 16: proto.LocationService.GetUpazilasByDistrict:output_type -> proto.GetUpazilasByDistrictResponse
	11, // 17: proto.EducationService.GetQualifications:output_type -> proto.GetQualificationsResponse
	14, // 18: proto.StaticDataService.GetReligions:output_type -> proto.GetReligionsResponse
	16, // 19: proto.StaticDataService.GetProfessions:output_type -> proto.GetProfessionsResponse
	18, // 20: proto.StaticDataService.GetMaritalStatuses:output_type -> proto.GetMaritalStatusesResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_matrimonial_proto_init() }
func file_matrimonial_proto_init() {
	if File_matrimonial_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matrimonial_proto_rawDesc), len(file_matrimonial_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_matrimonial_proto_goTypes,
		DependencyIndexes: file_matrimonial_proto_depIdxs,
		MessageInfos:      file_matrimonial_proto_msgTypes,
	}.Build()
	File_matrimonial_proto = out.File
	file_matrimonial_proto_goTypes = nil
	file_matrimonial_proto_depIdxs = nil
}
