// All RPC definitions
// proto/matrimonial.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: matrimonial.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocationService_GetDivisions_FullMethodName           = "/proto.LocationService/GetDivisions"
	LocationService_GetDistrictsByDivision_FullMethodName = "/proto.LocationService/GetDistrictsByDivision"
	LocationService_GetUpazilasByDistrict_FullMethodName  = "/proto.LocationService/GetUpazilasByDistrict"
	LocationService_GetUpazilaById_FullMethodName         = "/proto.LocationService/GetUpazilaById"
)

// LocationServiceClient is the client API for LocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocationServiceClient interface {
	GetDivisions(ctx context.Context, in *GetDivisionsRequest, opts ...grpc.CallOption) (*GetDivisionsResponse, error)
	GetDistrictsByDivision(ctx context.Context, in *GetDistrictsByDivisionRequest, opts ...grpc.CallOption) (*GetDistrictsByDivisionResponse, error)
	GetUpazilasByDistrict(ctx context.Context, in *GetUpazilasByDistrictRequest, opts ...grpc.CallOption) (*GetUpazilasByDistrictResponse, error)
	GetUpazilaById(ctx context.Context, in *GetUpazilaByIdRequest, opts ...grpc.CallOption) (*GetUpazilaByIdResponse, error)
}

type locationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocationServiceClient(cc grpc.ClientConnInterface) LocationServiceClient {
	return &locationServiceClient{cc}
}

func (c *locationServiceClient) GetDivisions(ctx context.Context, in *GetDivisionsRequest, opts ...grpc.CallOption) (*GetDivisionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDivisionsResponse)
	err := c.cc.Invoke(ctx, LocationService_GetDivisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) GetDistrictsByDivision(ctx context.Context, in *GetDistrictsByDivisionRequest, opts ...grpc.CallOption) (*GetDistrictsByDivisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDistrictsByDivisionResponse)
	err := c.cc.Invoke(ctx, LocationService_GetDistrictsByDivision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) GetUpazilasByDistrict(ctx context.Context, in *GetUpazilasByDistrictRequest, opts ...grpc.CallOption) (*GetUpazilasByDistrictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUpazilasByDistrictResponse)
	err := c.cc.Invoke(ctx, LocationService_GetUpazilasByDistrict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) GetUpazilaById(ctx context.Context, in *GetUpazilaByIdRequest, opts ...grpc.CallOption) (*GetUpazilaByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUpazilaByIdResponse)
	err := c.cc.Invoke(ctx, LocationService_GetUpazilaById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationServiceServer is the server API for LocationService service.
// All implementations must embed UnimplementedLocationServiceServer
// for forward compatibility.
type LocationServiceServer interface {
	GetDivisions(context.Context, *GetDivisionsRequest) (*GetDivisionsResponse, error)
	GetDistrictsByDivision(context.Context, *GetDistrictsByDivisionRequest) (*GetDistrictsByDivisionResponse, error)
	GetUpazilasByDistrict(context.Context, *GetUpazilasByDistrictRequest) (*GetUpazilasByDistrictResponse, error)
	GetUpazilaById(context.Context, *GetUpazilaByIdRequest) (*GetUpazilaByIdResponse, error)
	mustEmbedUnimplementedLocationServiceServer()
}

// UnimplementedLocationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocationServiceServer struct{}

func (UnimplementedLocationServiceServer) GetDivisions(context.Context, *GetDivisionsRequest) (*GetDivisionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDivisions not implemented")
}
func (UnimplementedLocationServiceServer) GetDistrictsByDivision(context.Context, *GetDistrictsByDivisionRequest) (*GetDistrictsByDivisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDistrictsByDivision not implemented")
}
func (UnimplementedLocationServiceServer) GetUpazilasByDistrict(context.Context, *GetUpazilasByDistrictRequest) (*GetUpazilasByDistrictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUpazilasByDistrict not implemented")
}
func (UnimplementedLocationServiceServer) GetUpazilaById(context.Context, *GetUpazilaByIdRequest) (*GetUpazilaByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUpazilaById not implemented")
}
func (UnimplementedLocationServiceServer) mustEmbedUnimplementedLocationServiceServer() {}
func (UnimplementedLocationServiceServer) testEmbeddedByValue()                         {}

// UnsafeLocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocationServiceServer will
// result in compilation errors.
type UnsafeLocationServiceServer interface {
	mustEmbedUnimplementedLocationServiceServer()
}

func RegisterLocationServiceServer(s grpc.ServiceRegistrar, srv LocationServiceServer) {
	// If the following call pancis, it indicates UnimplementedLocationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocationService_ServiceDesc, srv)
}

func _LocationService_GetDivisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDivisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GetDivisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_GetDivisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GetDivisions(ctx, req.(*GetDivisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_GetDistrictsByDivision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDistrictsByDivisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GetDistrictsByDivision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_GetDistrictsByDivision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GetDistrictsByDivision(ctx, req.(*GetDistrictsByDivisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_GetUpazilasByDistrict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUpazilasByDistrictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GetUpazilasByDistrict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_GetUpazilasByDistrict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GetUpazilasByDistrict(ctx, req.(*GetUpazilasByDistrictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_GetUpazilaById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUpazilaByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GetUpazilaById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_GetUpazilaById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GetUpazilaById(ctx, req.(*GetUpazilaByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocationService_ServiceDesc is the grpc.ServiceDesc for LocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.LocationService",
	HandlerType: (*LocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDivisions",
			Handler:    _LocationService_GetDivisions_Handler,
		},
		{
			MethodName: "GetDistrictsByDivision",
			Handler:    _LocationService_GetDistrictsByDivision_Handler,
		},
		{
			MethodName: "GetUpazilasByDistrict",
			Handler:    _LocationService_GetUpazilasByDistrict_Handler,
		},
		{
			MethodName: "GetUpazilaById",
			Handler:    _LocationService_GetUpazilaById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "matrimonial.proto",
}

const (
	EducationService_GetQualifications_FullMethodName = "/proto.EducationService/GetQualifications"
)

// EducationServiceClient is the client API for EducationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EducationServiceClient interface {
	GetQualifications(ctx context.Context, in *GetQualificationsRequest, opts ...grpc.CallOption) (*GetQualificationsResponse, error)
}

type educationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEducationServiceClient(cc grpc.ClientConnInterface) EducationServiceClient {
	return &educationServiceClient{cc}
}

func (c *educationServiceClient) GetQualifications(ctx context.Context, in *GetQualificationsRequest, opts ...grpc.CallOption) (*GetQualificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQualificationsResponse)
	err := c.cc.Invoke(ctx, EducationService_GetQualifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EducationServiceServer is the server API for EducationService service.
// All implementations must embed UnimplementedEducationServiceServer
// for forward compatibility.
type EducationServiceServer interface {
	GetQualifications(context.Context, *GetQualificationsRequest) (*GetQualificationsResponse, error)
	mustEmbedUnimplementedEducationServiceServer()
}

// UnimplementedEducationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEducationServiceServer struct{}

func (UnimplementedEducationServiceServer) GetQualifications(context.Context, *GetQualificationsRequest) (*GetQualificationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQualifications not implemented")
}
func (UnimplementedEducationServiceServer) mustEmbedUnimplementedEducationServiceServer() {}
func (UnimplementedEducationServiceServer) testEmbeddedByValue()                          {}

// UnsafeEducationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EducationServiceServer will
// result in compilation errors.
type UnsafeEducationServiceServer interface {
	mustEmbedUnimplementedEducationServiceServer()
}

func RegisterEducationServiceServer(s grpc.ServiceRegistrar, srv EducationServiceServer) {
	// If the following call pancis, it indicates UnimplementedEducationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EducationService_ServiceDesc, srv)
}

func _EducationService_GetQualifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQualificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).GetQualifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EducationService_GetQualifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).GetQualifications(ctx, req.(*GetQualificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EducationService_ServiceDesc is the grpc.ServiceDesc for EducationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EducationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EducationService",
	HandlerType: (*EducationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQualifications",
			Handler:    _EducationService_GetQualifications_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "matrimonial.proto",
}

const (
	StaticDataService_GetReligions_FullMethodName       = "/proto.StaticDataService/GetReligions"
	StaticDataService_GetProfessions_FullMethodName     = "/proto.StaticDataService/GetProfessions"
	StaticDataService_GetMaritalStatuses_FullMethodName = "/proto.StaticDataService/GetMaritalStatuses"
)

// StaticDataServiceClient is the client API for StaticDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StaticDataServiceClient interface {
	GetReligions(ctx context.Context, in *GetReligionsRequest, opts ...grpc.CallOption) (*GetReligionsResponse, error)
	GetProfessions(ctx context.Context, in *GetProfessionsRequest, opts ...grpc.CallOption) (*GetProfessionsResponse, error)
	GetMaritalStatuses(ctx context.Context, in *GetMaritalStatusesRequest, opts ...grpc.CallOption) (*GetMaritalStatusesResponse, error)
}

type staticDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStaticDataServiceClient(cc grpc.ClientConnInterface) StaticDataServiceClient {
	return &staticDataServiceClient{cc}
}

func (c *staticDataServiceClient) GetReligions(ctx context.Context, in *GetReligionsRequest, opts ...grpc.CallOption) (*GetReligionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReligionsResponse)
	err := c.cc.Invoke(ctx, StaticDataService_GetReligions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticDataServiceClient) GetProfessions(ctx context.Context, in *GetProfessionsRequest, opts ...grpc.CallOption) (*GetProfessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfessionsResponse)
	err := c.cc.Invoke(ctx, StaticDataService_GetProfessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticDataServiceClient) GetMaritalStatuses(ctx context.Context, in *GetMaritalStatusesRequest, opts ...grpc.CallOption) (*GetMaritalStatusesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMaritalStatusesResponse)
	err := c.cc.Invoke(ctx, StaticDataService_GetMaritalStatuses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StaticDataServiceServer is the server API for StaticDataService service.
// All implementations must embed UnimplementedStaticDataServiceServer
// for forward compatibility.
type StaticDataServiceServer interface {
	GetReligions(context.Context, *GetReligionsRequest) (*GetReligionsResponse, error)
	GetProfessions(context.Context, *GetProfessionsRequest) (*GetProfessionsResponse, error)
	GetMaritalStatuses(context.Context, *GetMaritalStatusesRequest) (*GetMaritalStatusesResponse, error)
	mustEmbedUnimplementedStaticDataServiceServer()
}

// UnimplementedStaticDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStaticDataServiceServer struct{}

func (UnimplementedStaticDataServiceServer) GetReligions(context.Context, *GetReligionsRequest) (*GetReligionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReligions not implemented")
}
func (UnimplementedStaticDataServiceServer) GetProfessions(context.Context, *GetProfessionsRequest) (*GetProfessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfessions not implemented")
}
func (UnimplementedStaticDataServiceServer) GetMaritalStatuses(context.Context, *GetMaritalStatusesRequest) (*GetMaritalStatusesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMaritalStatuses not implemented")
}
func (UnimplementedStaticDataServiceServer) mustEmbedUnimplementedStaticDataServiceServer() {}
func (UnimplementedStaticDataServiceServer) testEmbeddedByValue()                           {}

// UnsafeStaticDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StaticDataServiceServer will
// result in compilation errors.
type UnsafeStaticDataServiceServer interface {
	mustEmbedUnimplementedStaticDataServiceServer()
}

func RegisterStaticDataServiceServer(s grpc.ServiceRegistrar, srv StaticDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedStaticDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StaticDataService_ServiceDesc, srv)
}

func _StaticDataService_GetReligions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReligionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticDataServiceServer).GetReligions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaticDataService_GetReligions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticDataServiceServer).GetReligions(ctx, req.(*GetReligionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaticDataService_GetProfessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticDataServiceServer).GetProfessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaticDataService_GetProfessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticDataServiceServer).GetProfessions(ctx, req.(*GetProfessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaticDataService_GetMaritalStatuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMaritalStatusesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticDataServiceServer).GetMaritalStatuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaticDataService_GetMaritalStatuses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticDataServiceServer).GetMaritalStatuses(ctx, req.(*GetMaritalStatusesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StaticDataService_ServiceDesc is the grpc.ServiceDesc for StaticDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StaticDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StaticDataService",
	HandlerType: (*StaticDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetReligions",
			Handler:    _StaticDataService_GetReligions_Handler,
		},
		{
			MethodName: "GetProfessions",
			Handler:    _StaticDataService_GetProfessions_Handler,
		},
		{
			MethodName: "GetMaritalStatuses",
			Handler:    _StaticDataService_GetMaritalStatuses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "matrimonial.proto",
}
